// Package manifest defines the on-disk contract that describes a workspace and
// the services in it. Everything else in wharf reads from these types; nothing
// else is allowed to guess at how a service runs.
package manifest

// Kind classifies what a project is, which decides whether wharf can run it.
type Kind string

const (
	// KindService is a long-running process with a berth (port) and a health check.
	KindService Kind = "service"
	// KindLibrary is built or watched but never "started" — SDKs, plugins.
	KindLibrary Kind = "library"
	// KindInfra is a datastore or broker wharf brings up but does not develop.
	KindInfra Kind = "infra"
)

// Stack is the language/toolchain, used to pick a detector and a default runner.
type Stack string

const (
	StackGo     Stack = "go"
	StackNode   Stack = "node"
	StackPython Stack = "python"
	StackPHP    Stack = "php"
	StackDocker Stack = "docker"
	StackUnknown Stack = "unknown"
)

// ConfigFormat is how a service's configuration is encoded. The overlay engine
// has one reader/writer per format; adding TOML means adding one implementation,
// not touching any caller.
type ConfigFormat string

const (
	FormatYAML   ConfigFormat = "yaml"
	FormatDotenv ConfigFormat = "dotenv"
	FormatJSON   ConfigFormat = "json"
)

// Workspace is the root config: ~/.wharf/workspace.yaml. It deliberately holds
// no project-specific knowledge — just where to look and how to route.
type Workspace struct {
	// Roots are directories scanned for projects.
	Roots []string `yaml:"roots"`
	// BerthRange is the port range wharf may allocate from when resolving
	// collisions. Services with an explicit berth keep it.
	BerthRange BerthRange `yaml:"berth_range"`
	// Gateway configures the local API gateway, if any.
	Gateway GatewayConfig `yaml:"gateway,omitempty"`
}

// BerthRange bounds automatic port allocation.
type BerthRange struct {
	From int `yaml:"from"`
	To   int `yaml:"to"`
}

// GatewayConfig describes the local reverse proxy fronting the services.
type GatewayConfig struct {
	// Driver is "caddy", "nginx", or "" to disable gateway management.
	Driver string `yaml:"driver"`
	// Host is the virtual host services are routed under, e.g. api.tenbyte.test.
	Host string `yaml:"host"`
	// ConfigPath is where the generated gateway config is written.
	ConfigPath string `yaml:"config_path"`
	// ReloadCmd overrides the driver's default reload mechanism.
	ReloadCmd string `yaml:"reload_cmd,omitempty"`
}

// Service is one project: ~/.wharf/services/<name>.yaml. Generated by `wharf
// scan`, then hand-editable — detection is a starting point, not an authority.
type Service struct {
	Name string `yaml:"name"`
	Path string `yaml:"path"`
	Kind Kind   `yaml:"kind"`
	Stack Stack `yaml:"stack"`

	// Berth is the port this service owns. Stable across runs so that
	// dependents and gateway routes can hard-code it.
	Berth int `yaml:"berth,omitempty"`

	// Declared is the port the project's own config asked for when wharf first
	// saw it, before any berth was assigned.
	//
	// It is kept because the outside world still refers to services by their
	// original port: an existing nginx config routes /v1/cdn/ to :8085 because
	// that is what the CDN service used to declare. Matching such a route
	// against the *current* occupant of :8085 hands it to whichever service won
	// that port in the collision — silently routing traffic to the wrong
	// service.
	Declared int `yaml:"declared_berth,omitempty"`

	// Processes are the things to run. A service is a *group* — an API plus a
	// worker plus a poller are one service, started and killed together.
	Processes []Process `yaml:"processes,omitempty"`

	// Config lists this service's config sources, in precedence order.
	Config []ConfigSource `yaml:"config,omitempty"`

	// Needs are infra dependencies (postgres, redis, clickhouse, kafka).
	Needs []Need `yaml:"needs,omitempty"`

	// DependsOn are other wharf services that must be healthy first.
	DependsOn []string `yaml:"depends_on,omitempty"`

	// Health is how wharf decides the service is actually up.
	Health *Health `yaml:"health,omitempty"`

	// Lifecycle holds the setup commands that are otherwise only in your head.
	Lifecycle Lifecycle `yaml:"lifecycle,omitempty"`

	// Route, if set, registers this service with the gateway.
	Route *Route `yaml:"route,omitempty"`

	// Disabled excludes the service from `up all` without deleting the manifest.
	Disabled bool `yaml:"disabled,omitempty"`
}

// Process is a single command in a service's process group.
type Process struct {
	// Name distinguishes processes within a service: api, worker, poller.
	Name string `yaml:"name"`
	// Cmd is the command line, run via the shell in the service's directory.
	Cmd string `yaml:"cmd"`
	// Dir is relative to the service Path; empty means the service root.
	Dir string `yaml:"dir,omitempty"`
	// Env are extra environment variables for this process only.
	Env map[string]string `yaml:"env,omitempty"`
	// Primary marks the process that owns the berth and answers the health
	// check. Exactly one process per service should be primary.
	Primary bool `yaml:"primary,omitempty"`
	// Autostart false means the process exists in the manifest but is not
	// started by default (e.g. a poller you rarely need).
	Autostart *bool `yaml:"autostart,omitempty"`
}

// ShouldAutostart reports whether this process starts with the service.
// Defaults to true when unset, so a hand-written manifest need not say so.
func (p Process) ShouldAutostart() bool {
	return p.Autostart == nil || *p.Autostart
}

// ConfigSource is one config file belonging to a service.
type ConfigSource struct {
	Format ConfigFormat `yaml:"format"`
	// Path is relative to the service root, e.g. config/config.yaml or .env.
	Path string `yaml:"path"`
	// Template is the checked-in example this config should be diffed against,
	// so a missing key is reported before it becomes a runtime panic.
	Template string `yaml:"template,omitempty"`
	// PortKey is the dotted path (yaml/json) or key (dotenv) holding the listen
	// port, so wharf can rewrite it to the assigned berth.
	PortKey string `yaml:"port_key,omitempty"`

	// PortTemplate is the *shape* the value is stored in, with {port} standing
	// in for the number: "{port}", ":{port}", or "0.0.0.0:{port}".
	//
	// Without this, a config holding `addr: ":8080"` would be rewritten to
	// `addr: 8080` — a bare integer where the program expects a listen address,
	// which breaks it. Reading a port is not the same as knowing how to write
	// one back.
	PortTemplate string `yaml:"port_template,omitempty"`
	// Flag is how the process is told to use the generated config, e.g.
	// "-config". Empty means the config is read from its default location and
	// wharf must instead inject via environment.
	Flag string `yaml:"flag,omitempty"`
}

// Need is a piece of infrastructure a service requires.
type Need struct {
	// Type is postgres, redis, clickhouse, kafka, minio, ...
	Type string `yaml:"type"`
	// DSN is the connection string as read from the service's own config, so
	// `wharf db` can open a shell without you looking anything up.
	DSN string `yaml:"dsn,omitempty"`
	// Compose points at a compose file that provides this need, if one exists.
	Compose string `yaml:"compose,omitempty"`
	// ComposeService is the service name within that compose file.
	ComposeService string `yaml:"compose_service,omitempty"`
}

// Health is a readiness probe.
type Health struct {
	// Type is "tcp" or "http".
	Type string `yaml:"type"`
	// Path is the HTTP path to probe; ignored for tcp.
	Path string `yaml:"path,omitempty"`
	// TimeoutSeconds bounds how long `up` waits before declaring failure.
	TimeoutSeconds int `yaml:"timeout_seconds,omitempty"`
}

// Lifecycle records the setup commands for a project — the ones you currently
// have to rediscover by reading a README or a Makefile.
type Lifecycle struct {
	Install string `yaml:"install,omitempty"`
	Migrate string `yaml:"migrate,omitempty"`
	Seed    string `yaml:"seed,omitempty"`
	Build   string `yaml:"build,omitempty"`
	Test    string `yaml:"test,omitempty"`
}

// Route registers a service with the local gateway. The berth is not repeated
// here on purpose: the gateway generator reads Service.Berth, which is why a
// port change cannot silently desync from a route.
type Route struct {
	// Prefix is the path prefix on the gateway host, e.g. /v1/cdn/.
	Prefix string `yaml:"prefix"`

	// Strip removes Prefix from the path before proxying upstream.
	Strip bool `yaml:"strip,omitempty"`

	// UpstreamPrefix is prepended after stripping, so /v1/cdn/x becomes /v1/x.
	// Empty sends the stripped path unchanged.
	//
	// Strip and UpstreamPrefix are separate because nginx conflates them: the
	// trailing slash in `proxy_pass http://host:8082/` is what strips the
	// prefix, while `proxy_pass http://host:8082` keeps the whole URI. One field
	// cannot express both without getting a route quietly wrong.
	UpstreamPrefix string `yaml:"upstream_prefix,omitempty"`

	// Default marks the catch-all backend for "/".
	Default bool `yaml:"default,omitempty"`
}
