package gateway

import (
	"fmt"
	"strings"
	"text/template"
)

// Caddy generates a Caddyfile.
//
// Caddy is the recommended driver: snippets remove the per-route boilerplate
// that a hand-written nginx config repeats for every backend, WebSockets need no
// special directives (which matters for Centrifugo and LiveKit), and it
// provisions a trusted local certificate automatically — so cookie-based auth
// behaves the way it does in production.
type Caddy struct{}

func (Caddy) Name() string { return "caddy" }

// caddyTemplate is one snippet plus one line per route, rather than the same
// thirty-line proxy block copied per backend.
var caddyTemplate = template.Must(template.New("caddyfile").Parse(
	`# Generated by wharf. Do not edit — your changes will be overwritten.
#
# Every upstream below is derived from the service's assigned berth, so a route
# can never point at a port the service is not listening on.

(wharf_upstream) {
	header_up X-Real-IP {remote_host}
	header_up X-Forwarded-Proto {scheme}
	# Long timeouts: uploads and streaming responses are normal here.
	transport http {
		read_timeout 30m
		dial_timeout 10s
	}
}

(wharf_cors) {
	@wharf_preflight method OPTIONS
	handle @wharf_preflight {
		header Access-Control-Allow-Origin "{http.request.header.Origin}"
		header Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS"
		header Access-Control-Allow-Headers "Authorization, Content-Type, X-Domain, X-Requested-With"
		header Access-Control-Allow-Credentials "true"
		header Access-Control-Max-Age "86400"
		respond 204
	}
	header Access-Control-Allow-Origin "{http.request.header.Origin}"
	header Access-Control-Allow-Credentials "true"
}

{{ .Host }} {
	import wharf_cors
{{ range .Routes }}
	# {{ .Service }}
{{- if .Default }}
	handle {
		reverse_proxy localhost:{{ .Berth }} {
			import wharf_upstream
		}
	}
{{- else if .Strip }}
	handle_path {{ .Prefix }}* {
{{- if .UpstreamPrefix }}
		rewrite * {{ .UpstreamPrefix }}{uri}
{{- end }}
		reverse_proxy localhost:{{ .Berth }} {
			import wharf_upstream
		}
	}
{{- else }}
	handle {{ .Prefix }}* {
		reverse_proxy localhost:{{ .Berth }} {
			import wharf_upstream
		}
	}
{{- end }}
{{ end }}}
`))

func (c Caddy) Render(host string, routes []Route) (string, error) {
	if host == "" {
		return "", fmt.Errorf("gateway.host is not set")
	}

	var b strings.Builder
	err := caddyTemplate.Execute(&b, struct {
		Host   string
		Routes []Route
	}{Host: host, Routes: routes})
	if err != nil {
		return "", fmt.Errorf("render caddyfile: %w", err)
	}
	return b.String(), nil
}

// Reload asks the running Caddy to adopt the new config. Caddy validates before
// swapping, so a bad config leaves the old one serving rather than taking the
// gateway down.
func (Caddy) Reload(configPath string) error {
	return run("caddy", "reload", "--config", configPath, "--adapter", "caddyfile")
}
