package gateway

import (
	"fmt"
	"strings"
	"text/template"
)

// Nginx generates an nginx server block.
//
// It exists so that adopting wharf does not force a proxy migration: the routes
// keep working exactly as they do today. The output is verbose because nginx has
// no snippet mechanism worth the name — which is precisely the argument for
// generating it rather than maintaining it by hand.
type Nginx struct{}

func (Nginx) Name() string { return "nginx" }

var nginxTemplate = template.Must(template.New("nginx").Parse(`# Generated by wharf. Do not edit — your changes will be overwritten.
#
# Every upstream below is derived from the service's assigned berth, so a route
# can never point at a port the service is not listening on.

map $http_origin $wharf_cors_origin {
    default "";
    "~^http://localhost(:[0-9]+)?$"   $http_origin;
    "~^http://127\.0\.0\.1(:[0-9]+)?$" $http_origin;
}

server {
    listen 127.0.0.1:80;
    server_name {{ .Host }};
    charset utf-8;
    client_max_body_size 128M;
    access_log off;
{{ range .Routes }}
    # {{ .Service }}
    location {{ if .Default }}/{{ else }}^~ {{ .Prefix }}{{ end }} {
        proxy_hide_header Access-Control-Allow-Origin;
        proxy_hide_header Access-Control-Allow-Credentials;
        proxy_hide_header Access-Control-Allow-Methods;
        proxy_hide_header Access-Control-Allow-Headers;

        if ($request_method = OPTIONS) {
            add_header Access-Control-Allow-Origin      $wharf_cors_origin always;
            add_header Access-Control-Allow-Methods     "GET, POST, PUT, PATCH, DELETE, OPTIONS" always;
            add_header Access-Control-Allow-Headers     "Authorization, Content-Type, X-Domain, X-Requested-With" always;
            add_header Access-Control-Allow-Credentials "true" always;
            add_header Access-Control-Max-Age           86400 always;
            return 204;
        }

        add_header Access-Control-Allow-Origin      $wharf_cors_origin always;
        add_header Access-Control-Allow-Credentials "true" always;

        proxy_pass http://localhost:{{ .Berth }}{{ .NginxProxyPath }};
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_http_version 1.1;
        proxy_read_timeout    1800;
        proxy_connect_timeout 1800;
        chunked_transfer_encoding on;
        proxy_redirect off;
        proxy_buffering off;
    }
{{ end }}}
`))

func (n Nginx) Render(host string, routes []Route) (string, error) {
	if host == "" {
		return "", fmt.Errorf("gateway.host is not set")
	}

	var b strings.Builder
	err := nginxTemplate.Execute(&b, struct {
		Host   string
		Routes []Route
	}{Host: host, Routes: routes})
	if err != nil {
		return "", fmt.Errorf("render nginx config: %w", err)
	}
	return b.String(), nil
}

// Reload validates the config before asking nginx to adopt it. Reloading an
// invalid config takes the gateway down for every service at once.
func (Nginx) Reload(string) error {
	if err := run("nginx", "-t"); err != nil {
		return fmt.Errorf("config is invalid, not reloading: %w", err)
	}
	return run("nginx", "-s", "reload")
}
